###
POST  https://cookingtech.herokuapp.com/api/login
Content-Type: application/json

{
    "email": "aparece@gmail.com",
    "password": "password"
}
###

POST https://cookingtech.herokuapp.com/api/recipes
Content-Type: application/json

{
    "name": "Adobo",
    "description": "lami",
    "ingredients": "['test','test','test']",
    "procedure": "['test','test']",
    "tag": "[yummy]",
    "category": "desert",
    "yeild": 5,
    "video_url": "fasfasfasfas",
    "img_url": "afasfasfsafasfasf"
}

####

GET https://cookingtech.herokuapp.com/api/recipes

